<?php
/**
 * @version 8.0 [rev.8.0.01]
 */

$categories = $this->categories()->getData();

/** @var \Ppb\Service\Table\Relational\Categories $categoriesService */
$categoriesService = $this->categories()->getCategories();
if (!count($categories)) {
    $categories = $this->categories(
        $categoriesService->getTable()
            ->select()
            ->where('parent_id IS NULL')
            ->where('enable_auctions = ?', 1)
            ->where('user_id IS NULL')
            ->order(array('order_id ASC', 'name ASC'))
    );
}

/** @var \Cube\Controller\Request $request */
$request = $this->request()->getRequest();

$categoryId = $request->getParam('category_id');
$parentId = $request->getParam('parent_id');

// header links
$headerLinksWelcomeUser = $this->headerLinks('partials/header-links-welcome-user.phtml')->render();
$headerLinksDesktop = $this->headerLinks('partials/header-links-desktop.phtml')->render();
$headerLinksMobile = $this->headerLinks('partials/header-links-mobile.phtml')->render();

// cart dropdown
$cartDropdown = $this->cart(null, 'partials/cart-dropdown.phtml')->dropdown();
?>

<!-- NAVIGATION FOR LG & UP -->
<div class="d-none d-lg-block desktop-navbar">
    <div class="container">
        <!-- HEADER NAVIGATION -->
        <nav class="navbar navbar-expand-lg px-0">
            <a class="navbar-brand" href="<?php echo $this->url(null, 'app-home'); ?>"
               title="<?php echo $this->settings['sitename']; ?>">
                <img src="<?php echo $this->thumbnail()->generateImagePath($this->settings['site_logo_path']); ?>"
                     class="img-fluid"
                     alt="<?php echo $this->settings['sitename']; ?>">
            </a>
            <div class="collapse navbar-collapse">
                <div class="ml-2">
                    <small class="au-welcome-user">
                        <?php echo $headerLinksWelcomeUser; ?>
                    </small>

                    <div class="au-links-desktop">
                        <?php echo $headerLinksDesktop; ?>
                    </div>
                </div>

                <ul class="navbar-nav nav-main-menu ml-auto">
                    <?php foreach ($this->menu->pages as $page) { ?>
                        <?php if ((!$page->settings || (intval($this->settings[(string)$page->settings['name']]) == $page->settings['value'])) &&
                            ($this->navigation()->accept($page)) && $page->hidden != 'true'
                        ) {
                            ?>
                            <li class="nav-item <?php echo ($page->isActive(true)) ? 'active' : ''; ?>">
                                <a class="nav-link"
                                   href="<?php echo $this->url($page->params); ?>">
                                    <?php echo $page->label; ?>
                                </a>
                            </li>
                        <?php } ?>
                    <?php } ?>

                    <?php if ($cartDropdown) { ?>
                        <li class="nav-item au-cart-dropdown">
                            <?php echo $cartDropdown; ?>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </nav>

        <!-- /HEADER NAVIGATION -->

        <!-- SEARCH BAR -->
        <nav class="navbar navbar-light navbar-expand-lg nav-search mt-1 mb-4">
            <div class="row">
                <!-- BROWSE CATEGORIES DROPDOWN -->
                <div class="col-2">
                    <div class="dropdown categories-dropdown">
                        <button class="btn btn-block btn-icon dropdown-toggle" type="button" id="categoriesDropdown"
                                data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="true">
                            <span><?php echo $this->_('Categories'); ?></span>
                            <span data-feather="chevron-down"></span>
                        </button>

                        <div class="dropdown-menu" aria-labelledby="categoriesDropdown">
                            <div class="row">
                                <?php
                                /** @var \Ppb\Db\Table\Row\Category $category */
                                foreach ($categories as $category) {
                                    $counter = $category->getCounter();

                                    if ($counter > 0 || !$this->settings['hide_empty_categories']) {
                                        ?>
                                        <div class="col-6 categories-item pb-1">
                                            <a href="<?php echo $this->url($category->link()); ?>">
                                                <?php echo $this->_($category['name']); ?>
                                            </a>

                                            <?php
                                            if ($this->settings['category_counters']) {
                                                echo '<small>(' . $counter . ')</small>';
                                            }
                                            ?>

                                        </div>
                                    <?php } ?>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /BROWSE CATEGORIES DROPDOWN -->

                <div class="col">
                    <!-- SEARCH FORM -->
                    <form id="form-header-search" class="row"
                          action="<?php echo $this->url(null, 'listings-search'); ?>"
                          method="get">
                        <?php echo $this->formElement('hidden', 'parent_id')
                            ->setValue($request->getParam('parent_id'))
                            ->render();
                        ?>
                        <div class="col-4 px-0">
                            <ul id="category-select-content">
                                <li>
                                    <a href="#"
                                       data-id=""
                                       data-category-name="<?php echo $this->_('All Categories'); ?>">
                                        <?php echo $this->_('All Categories'); ?>
                                    </a>
                                </li>
                                <?php
                                $selectedCategory = $this->_('Choose Category');
                                $maxChars = 20;

                                /** @var \Ppb\Db\Table\Row\Category $category */
                                foreach ($categories as $category) {
                                    $shortCategoryName = $this->_($category['name']);
                                    $length = strlen($shortCategoryName);
                                    $shortCategoryName = substr($shortCategoryName, 0, $maxChars) . (($length > $maxChars) ? '...' : '');

                                    if ($category['id'] == $request->getParam('parent_id')) {
                                        $selectedCategory = $shortCategoryName;
                                    }
                                    ?>
                                    <li>
                                        <a href="<?php echo $this->url($category->link()); ?>"
                                           data-id="<?php echo $category['id']; ?>"
                                           data-category-name="<?php echo $shortCategoryName; ?>">
                                            <?php echo $this->_($category['name']); ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                            <a id="category-select-btn" class="form-control" href="#">
                                <span><?php echo $selectedCategory; ?></span> <span data-feather="chevron-down"></span>
                            </a>
                        </div>
                        <div class="col px-1">
                            <input id="basic-search" type="text" name="keywords" class="form-control"
                                   value="<?php echo $request->getParam('keywords'); ?>"
                                   placeholder="<?php echo $this->_('Search...'); ?>">
                        </div>
                        <div class="col-auto px-0">
                            <button type="submit"
                                    class="btn btn-primary"><?php echo $this->_('Search'); ?></button>
                        </div>
                    </form>
                    <!-- /SEARCH FORM -->
                </div>

                <!-- ADVANCED SEARCH LINK -->
                <div class="col-auto">
                    <a class="btn btn-link"
                       href="<?php echo $this->url(array('module' => 'listings', 'controller' => 'search', 'action' => 'advanced')); ?>"><?php echo $this->_('Advanced'); ?></a>
                </div>
                <!-- /ADVANCED SEARCH LINK -->

                <!-- LANGUAGE BAR -->
                <div class="col-auto">
                    <?php echo $this->language()->render(); ?>
                </div>
                <!-- /LANGUAGE BAR -->
            </div>
        </nav>
        <!-- /SEARCH BAR -->
    </div>
</div>
<!-- /NAVIGATION FOR LG & UP -->

<!-- NAVIGATION FOR MD & LOWER -->
<div class="d-block d-lg-none mobile-navbar">
    <nav class="navbar" id="mobileNavbar">
        <button type="button" data-toggle="collapse" data-target="#mobileHeaderMenu"
                aria-expanded="false" aria-controls="mobileHeaderMenu">
            <span data-feather="menu"></span>
        </button>

        <a class="navbar-brand" href="<?php echo $this->url(null, 'app-home'); ?>"
           title="<?php echo $this->settings['sitename']; ?>">
            <img src="<?php echo $this->thumbnail()->generateImagePath($this->settings['site_logo_path']); ?>"
                 class="img-fluid"
                 alt="<?php echo $this->settings['sitename']; ?>">
        </a>

        <button type="button" data-toggle="collapse" data-target="#mobileSearchForm"
                aria-expanded="false" aria-controls="mobileSearchForm">
            <span data-feather="search"></span>
        </button>

        <?php if ($cartDropdown) { ?>
            <div class="au-cart-dropdown">
                <?php echo $cartDropdown; ?>
            </div>
        <?php } ?>

        <!-- SEARCH FORM -->
        <div class="collapse" id="mobileSearchForm">
            <form action="<?php echo $this->url(null, 'listings-search'); ?>"
                  method="get">

                <div class="has-icons">
                    <?php echo $this->formElement('text', 'keywords')
                        ->setValue($request->getParam('keywords'))
                        ->setAttributes(array(
                            'id'          => 'basic-search',
                            'placeholder' => $this->_('Search...'),
                            'class'       => 'form-control has-icon-right'
                        ))->render(); ?>
                    <span class="glyphicon glyphicon-search btn-icon-search icon-right"></span>
                </div>
            </form>
        </div>
        <!-- /SEARCH FORM -->

        <!-- HEADER MENU -->
        <div class="collapse" id="mobileHeaderMenu">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <div class="d-flex justify-content-between">
                        <small class="au-welcome-user">
                            <?php echo $headerLinksWelcomeUser; ?>
                        </small>

                        <!-- LANGUAGE BAR -->
                        <?php echo $this->language()->render(); ?>
                        <!-- /LANGUAGE BAR -->
                    </div>
                </li>
                <?php foreach ($this->menu->pages as $page) { ?>
                    <?php if ((!$page->settings || (intval($this->settings[(string)$page->settings['name']]) == $page->settings['value'])) &&
                        ($this->navigation()->accept($page)) && $page->hidden != 'true'
                    ) {
                        ?>
                        <li class="nav-item <?php echo ($page->isActive(true)) ? 'active' : ''; ?>">
                            <a class="nav-link"
                               href="<?php echo $this->url($page->params); ?>">
                                <?php echo $page->label; ?>
                            </a>
                        </li>
                    <?php } ?>
                <?php } ?>

                <li class="nav-item">
                    <a class="nav-link"
                       href="<?php echo $this->url(array('module' => 'members', 'controller' => 'tools', 'action' => 'watched-items')); ?>"
                       title="<?php echo $this->_('Wish List'); ?>"><?php echo $this->_('Wish List'); ?></a>
                </li>

                <li class="nav-item au-links-mobile">
                    <?php echo $headerLinksMobile; ?>
                </li>
            </ul>
        </div>
        <!-- /HEADER MENU -->
    </nav>

</div>
<!-- /NAVIGATION FOR MD & LOWER -->
