<?php
/**
 * @version 8.4 [rev.8.4.02]
 */
/** @var \Ppb\Db\Table\Row\Listing $listingModel */

/** @var array $listingFees */

use Cube\Form\Element\Submit as SubmitElement;

/** @var \Ppb\Service\Fees\ListingSetup $listingSetupService */

$listingModel
    ->addData('id', 0)
    ->addData('user_id', $this->loggedInUser['id'])
    ->addData('active', 0)
    ->addData('approved', 0);

$currentStep = $this->form->getCurrentStep();

echo $this->partial('partials/form-steps-header.phtml', array('form' => $this->form));
?>

<div class="form-listing">
    <!-- SITE MESSAGES -->
    <?php
    if (count($this->messages) > 0) {
        echo $this->actionMessages()->setMessages($this->messages)->render();
        $this->messages = [];
    }
    ?>
    <!-- /SITE MESSAGES -->

    <?php if ($currentStep == 'preview') {
        $includedForms = [];

        if ($listingModel->isAuction()) {
            $includedForms[] = 'bid';
        }

        if ($listingModel->isBuyOut()) {
            if ($listingModel->isShoppingCart() === true) {
                $includedForms[] = 'cart';
            }
            else {
                $includedForms[] = 'buy';
            }
        }

        if ($listingModel->isMakeOffer()) {
            $includedForms[] = 'offer';
        }

        $purchaseForm = new \Listings\Form\Purchase($includedForms, $listingModel);
        $purchaseForm->setDetails(true);
        ?>
        <h5 class="subtitle">
            <?php echo $this->_('Listing Preview'); ?>
        </h5>

        <div class="mb-5">
            <?php
            echo $this->partial('listings/listing/details.phtml', array(
                'listing'      => $listingModel,
                'seller'       => $listingModel->findParentRow('\Ppb\Db\Table\Users'),
                'purchaseForm' => $purchaseForm,
                'live'         => false
            )); ?>
        </div>

    <?php } ?>


    <form action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>"
          enctype="multipart/form-data" class="form-horizontal">
        <?php echo $this->form->getHiddenElements(true); ?>

        <?php if ($currentStep == 'preview') { ?>
            <div class="mb-4">
                <h5 class="subtitle">
                    <?php echo $this->_('Listing Setup Fees'); ?>
                </h5>

                <div class="mb-3">
                    <?php echo $this->partial('partials/voucher-code.phtml', array('userId' => null)); ?>
                </div>

                <dl class="row dl-lg">
                    <?php if (count($listingFees) > 0) { ?>
                        <?php foreach ($listingFees as $row) { ?>
                            <dt class="col-3 col-sm-2"><?php echo $this->_($row['name']); ?></dt>
                            <dd class="col-9 col-sm-10"><?php echo $this->amount($row['amount']); ?></dd>
                        <?php } ?>
                    <?php } ?>
                    <dt class="col-3 col-sm-2 fees-total"><?php echo $this->_('Total'); ?></dt>
                    <dd class="col-9 col-sm-10 fees-total"><?php echo $this->amount($listingSetupService->getTotalAmount()); ?>
                    </dd>
                </dl>
            </div>

            <?php if ($this->settings['listing_terms_box']) { ?>
                <h5 class="subtitle">
                    <?php echo $this->_('Terms and Conditions'); ?>
                </h5>
                <div class="card mb-4">
                    <div class="card-body well-scrollable">
                        <?php
                        $listingTerms = explode("\n", $this->settings['listing_terms_content']);
                        foreach ($listingTerms as $key => $paragraph) {
                            $listingTerms[$key] = $this->_(trim($paragraph));
                        }

                        echo implode('<br>', $listingTerms);
                        ?>
                    </div>
                </div>
            <?php } ?>
        <?php } ?>

        <?php foreach ($this->form->getElements() as $element) {
            if (!$element->isHidden() && !$element instanceof SubmitElement) {
                ?>
                <?php echo $this->partial('partials/form-element.phtml', array('element' => $element)); ?>
            <?php }
        } ?>

        <div class="my-5 pt-3 border-top d-flex justify-content-between form-buttons">
            <?php echo $this->partial('partials/form-submit-buttons.phtml', ['form' => $this->form]); ?>
        </div>
    </form>
</div>
